services:
  # 前端服务
  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_BASE_URL=http://backend:8000/api/v1
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  # 后端API服务
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    # depends_on:
    #   - database
    volumes:
      - ./logs:/app/logs
      - ./backend/config.yaml:/app/config.yaml
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL 数据库
  # database:
  #   image: postgres:17
  #   environment:
  #     - POSTGRES_DB=travel_planner
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=${DB_PASSWORD:-IDoNotKnow}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   restart: unless-stopped

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: travel_planner_network
    driver: bridge
