from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = "0.0.2"
down_revision: Union[str, None] = "0.0.1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # 先添加可为NULL的列
    op.add_column(
        "user", sa.Column("preferences_configured", sa.Boolean(), nullable=True, comment="是否已配置过偏好设置")
    )
    # 更新所有现有用户的默认值为False
    op.execute('UPDATE "user" SET preferences_configured = false WHERE preferences_configured IS NULL')
    # 将列改为NOT NULL
    op.alter_column("user", "preferences_configured", nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "preferences_configured")
    # ### end Alembic commands ###
